### ISSUE TITLE
IMDB is blocking all images

### ISSUE THREAD

**Issue by bbondy** [brave/chromium#28] opened 2016-10-09 02:17 UTC
http://m.imdb.com/name/nm1343484/

**Comment by SergeyZhukovsky** [comment] 2016-10-10 18:52
Could you please retry it with a stable version of chromium
https://github.com/brave/chromium/releases/tag/v.1.0.0beta
I cannot reproduce it with it
![imdb](https://cloud.githubusercontent.com/assets/12011303/19247403/2c1eb6fc-8ef9-11e6-9542-4f96565fcb9d.png)

**Comment by SergeyZhukovsky** [comment] 2016-10-11 21:06
@bbondy Does that work? Can I close it?

**Comment by SergeyZhukovsky** [comment] 2016-10-13 10:49
It is fixed in the latest version.

**Closed by SergeyZhukovsky** 2016-10-13 10:49 UTC
